#!/usr/bin/env bash
# red-only-followup-create.sh — RED-only PR の merge 後 follow-up Issue を draft で起票
#
# Issue #1613 AC3: PR #1608 で「red-only label + 手動 merge」により test 11 件 RED が main に
# 滞留した regression を防ぐ defense-in-depth Layer 5 (post-REJECT follow-up)。
# merge-gate REJECT 状態の red-only label 付き PR で本スクリプトを起動し、follow-up
# Issue（GREEN 実装 PR を起票するための tracking Issue）を draft で生成する。
#
# Usage:
#   bash red-only-followup-create.sh \
#     --pr-number <N> \
#     [--issue-title <title>] \
#     [--merge-gate-result REJECTED|MERGED|...] \
#     [--labels <comma-separated>] \
#     [--body-file <path>] \
#     [--dry-run]
#
# Exit:
#   0 — 起票成功 (draft Issue 番号を stdout に出力) または dry-run
#   1 — 引数不足 / gh CLI 失敗

set -uo pipefail

PR_NUMBER=""
ISSUE_TITLE=""
MG_RESULT=""
LABELS=""
BODY_FILE=""
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --pr-number)         PR_NUMBER="$2";   shift 2 ;;
    --issue-title)       ISSUE_TITLE="$2"; shift 2 ;;
    --merge-gate-result) MG_RESULT="$2";   shift 2 ;;
    --labels)            LABELS="$2";      shift 2 ;;
    --body-file)         BODY_FILE="$2";   shift 2 ;;
    --dry-run)           DRY_RUN=1;        shift ;;
    -h|--help)
      sed -n '1,/^set -uo/p' "$0" | sed 's/^# \{0,1\}//' >&2
      exit 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1 ;;
  esac
done

if [[ -z "$PR_NUMBER" ]]; then
  echo "Usage: red-only-followup-create.sh --pr-number <N> [--issue-title <title>] ..." >&2
  exit 1
fi

if [[ -z "$ISSUE_TITLE" ]]; then
  ISSUE_TITLE="follow-up: RED-only PR #${PR_NUMBER} の GREEN 実装"
fi

# label 文字列のデフォルト: red-only-followup
if [[ -z "$LABELS" ]]; then
  LABELS="red-only-followup"
fi

# body 生成 (--body-file が指定されればそれを採用、無ければ inline テンプレ)
TMP_BODY=""
if [[ -n "$BODY_FILE" && -f "$BODY_FILE" ]]; then
  body_arg=( --body-file "$BODY_FILE" )
else
  TMP_BODY=$(mktemp)
  cat > "$TMP_BODY" <<EOF
## 概要

PR #${PR_NUMBER} は RED-only test PR として merge されました。
本 Issue は GREEN 実装（test を通す production code）の追跡用 follow-up です。

## 背景

- 元 PR: #${PR_NUMBER}
- merge-gate result: ${MG_RESULT:-UNKNOWN}
- labels: ${LABELS}

## やること

- [ ] 元 PR で追加された RED テストを通す実装を作成
- [ ] 全 AC が満たされていることを verify
- [ ] PR を作成し本 Issue を Closes リンクで紐付け

## 不変条件

- 不変条件 R (content-REJECT override 禁止): 本 Issue が close されるまで元 PR の
  content-REJECT (RED-only state) は未解決。manual merge override は禁止される。

> Auto-generated by \`scripts/red-only-followup-create.sh\` (Issue #1613 AC3)
EOF
  body_arg=( --body-file "$TMP_BODY" )
fi

cleanup() {
  if [[ -n "$TMP_BODY" && -f "$TMP_BODY" ]]; then
    rm -f "$TMP_BODY"
  fi
}
trap cleanup EXIT

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "draft follow-up Issue (dry-run):"
  echo "  title: $ISSUE_TITLE"
  echo "  labels: $LABELS"
  echo "  body:"
  if [[ -n "$BODY_FILE" && -f "$BODY_FILE" ]]; then
    sed 's/^/    /' "$BODY_FILE"
  else
    sed 's/^/    /' "$TMP_BODY"
  fi
  exit 0
fi

# gh issue create --draft で follow-up Issue を作成
issue_url=""
if ! issue_url=$(gh issue create \
  --title "$ISSUE_TITLE" \
  --label "$LABELS" \
  --draft \
  "${body_arg[@]}" 2>&1); then
  echo "ERROR: gh issue create 失敗" >&2
  echo "$issue_url" >&2
  exit 1
fi

echo "draft follow-up Issue created: $issue_url"
exit 0
